Contact centre case lookup
ONSdigital/census-rm-case-api-2021 pull request #1
Opened 2019-05-20 09:01 UTC by AdeHarrison

# Motivation and Context
A new service providing endpoints for contact centre operatives into Census

# What has changed
Created 3 endpoints for searching by Case Id, UPRN & Case Reference

# How to test?
make test

# Links
[Trello](https://trello.com/c/Tg697scy/633-rmc-139-provide-case-look-up-for-cc-13)

2019-05-20 09:02 UTC, AdeHarrison commented
![](https://github.trello.services/images/mini-trello-icon.png) [RMC-139 Provide case look up for CC (13)](https://trello.com/c/Tg697scy/633-rmc-139-provide-case-look-up-for-cc-13)

2019-05-20 09:11 UTC, NickGrantONS commented on .maven.settings.xml
> +  <profiles>
Don't need this Artifactory profile - we're not using any Artifactory dependencies.

2019-05-20 09:12 UTC, NickGrantONS commented on .maven.settings.xml
> +  <profiles>
In fact, this entire file shouldn't exist - it existed for convenience on the old RM project, for devs to copy into their own `.m2` directories - no longer a dev setup step

2019-05-20 09:16 UTC, NickGrantONS commented on pom.xml
> +      <artifactId>unirest-java</artifactId>
this should be marked as `<scope>test</scope>` and put into the test dependencies section

2019-05-20 09:57 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/caseapisvc/endpoint/CaseEndpoint.java
> +    List<CaseContainerDTO> caseContainerDTOs = new ArrayList<>();
`LinkedList` is more efficient than `ArrayList` when the initial size is not specified.

2019-05-20 09:59 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/caseapisvc/endpoint/CaseEndpoint.java
> +    UPRNNotFoundException.class,
I think we should probably just have a generic "not found" exception.

2019-05-20 10:02 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/caseapisvc/endpoint/CaseEndpoint.java
> +      @PathVariable("caseId") String caseId,
If you use `UUID` as the type, then Spring will automatically return a 400 BAD REQUEST if the case ID is not a UUID

2019-05-20 10:03 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/caseapisvc/exception/CaseIdInvalidException.java
> +public class CaseIdInvalidException extends RuntimeException {
This exception is not needed if you use `UUID` instead of `String` as the type in the endpoint declaration

2019-05-20 10:04 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/caseapisvc/exception/CaseIdNotFoundException.java
> +public class CaseIdNotFoundException extends RuntimeException {
I think you can create a generic "not found" exception

2019-05-20 10:10 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/caseapisvc/model/entity/Case.java
> +  @Column @Transient private String caseType;
`caseType` is `addressType`

2019-05-20 10:12 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/caseapisvc/model/entity/Case.java
> +  @Column @Transient private String createdDateTime;
we should be able to calculate this from the `Event`s associated with the Case - we might need to bring in that part of the schema, although we also need the `eventType` to find the `CASE_CREATED` event.

2019-05-20 10:15 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/caseapisvc/model/entity/Event.java
> +  @Column @Transient private String eventType;
This is likely to be an `enum` called `EventType` - worth coding it as such?

2019-05-20 10:16 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/caseapisvc/service/CaseService.java
> +  private UUID validateAndConvertCaseIdToUUID(String caseId) {
this is not needed if we switch to `UUID` from `String` on the endpoint definition

2019-05-20 10:19 UTC, NickGrantONS commented on src/test/resources/application-test.yml
> +      ddl-auto: create
We should spin up the CaseProcessor in a docker container in order to create the DB

2019-05-20 10:20 UTC, NickGrantONS commented on src/test/resources/data-test.sql
> +delete from casev2.event;
truncate table is faster

2019-05-20 10:20 UTC, NickGrantONS commented on src/test/resources/data-test.sql
> +delete from casev2.uac_qid_link;
truncate table is faster

2019-05-20 10:20 UTC, NickGrantONS commented on src/test/resources/data-test.sql
> +delete from casev2.cases;
truncate table is faster

2019-05-20 10:28 UTC, NickGrantONS commented on src/test/resources/docker-compose.yml
> +  postgres-database:
if we add the Case Processor to this, then it will create its DB on startup, so we don't have to. We'll also need the docker container `dadarek/wait-for-dependencies` which makes everything wait until the containers are healthy - see Case Processor's code

2019-05-20 10:29 UTC, NickGrantONS commented on src/test/resources/schema.sql
> +CREATE SCHEMA IF NOT EXISTS casev2;
we can use the CaseProcessor docker image to create the schema if we add it to the `docker-compose.yml`. See comment above.

2019-05-20 10:30 UTC, NickGrantX requested changes
Some minor stuff, but might simplify a couple of areas / get rid of some unnecessary code.

Big one is that we can use the CaseProcessor docker image to create the DB using Docker Compose. See comments.

2019-05-21 06:36 UTC, AdeHarrison commented on .maven.settings.xml
> +  <profiles>
fixed

2019-05-21 06:38 UTC, AdeHarrison commented on pom.xml
> +      <artifactId>unirest-java</artifactId>
fixed

2019-05-21 06:51 UTC, AdeHarrison commented on src/main/java/uk/gov/ons/census/caseapisvc/endpoint/CaseEndpoint.java
> +      @PathVariable("caseId") String caseId,
@davidmort wants this as a 404

2019-05-21 06:51 UTC, AdeHarrison commented on src/main/java/uk/gov/ons/census/caseapisvc/endpoint/CaseEndpoint.java
> +    UPRNNotFoundException.class,
disagree

2019-05-21 06:51 UTC, AdeHarrison commented on src/main/java/uk/gov/ons/census/caseapisvc/endpoint/CaseEndpoint.java
> +    List<CaseContainerDTO> caseContainerDTOs = new ArrayList<>();
done

2019-05-21 07:00 UTC, AdeHarrison commented on src/test/resources/data-test.sql
> +delete from casev2.event;
changed

2019-05-21 07:00 UTC, AdeHarrison commented on src/test/resources/data-test.sql
> +delete from casev2.uac_qid_link;
changed

2019-05-21 07:00 UTC, AdeHarrison commented on src/test/resources/data-test.sql
> +delete from casev2.cases;
changed

2019-05-21 07:06 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/caseapisvc/endpoint/CaseEndpoint.java
> +    UPRNNotFoundException.class,
what value is there in having multiple "not found" exceptions?

2019-05-21 07:12 UTC, davidmort requested changes

2019-05-21 07:12 UTC, davidmort commented on README.md
> +This service is for use by the Contact Centre and provides a read-only API into the new (v2) case service.
```suggestion
This service provides a read-only API into for case details.
```

2019-05-21 12:36 UTC, AdeHarrison commented on src/main/java/uk/gov/ons/census/caseapisvc/model/entity/Case.java
> +  @Column @Transient private String caseType;
changed

2019-05-21 12:40 UTC, AdeHarrison commented on src/main/java/uk/gov/ons/census/caseapisvc/model/entity/Event.java
> +  @Column @Transient private String eventType;
changed

2019-05-22 08:17 UTC, AdeHarrison commented on README.md
> +This service is for use by the Contact Centre and provides a read-only API into the new (v2) case service.
done

2019-05-22 08:23 UTC, AdeHarrison commented on src/main/java/uk/gov/ons/census/caseapisvc/endpoint/CaseEndpoint.java
> +    UPRNNotFoundException.class,
more down to personal choice, IMO it's more readable and easier to test

2019-05-22 09:42 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/caseapisvc/model/entity/Event.java
> +  @Column @Transient private EventType eventType;
This code is now ready to copy from this PR: `https://github.com/ONSdigital/census-rm-case-processor/pull/10`

2019-05-22 09:57 UTC, AdeHarrison commented on src/main/java/uk/gov/ons/census/caseapisvc/model/entity/Event.java
> +  @Column @Transient private EventType eventType;
done

2019-05-22 09:57 UTC, AdeHarrison commented on src/test/resources/schema.sql
> +CREATE SCHEMA IF NOT EXISTS casev2;
done

2019-05-22 09:58 UTC, AdeHarrison commented on src/test/resources/docker-compose.yml
> +  postgres-database:
done

2019-05-22 09:58 UTC, AdeHarrison commented on src/test/resources/application-test.yml
> +      ddl-auto: create
done

2019-05-22 09:59 UTC, AdeHarrison commented on src/main/java/uk/gov/ons/census/caseapisvc/exception/CaseIdInvalidException.java
> +public class CaseIdInvalidException extends RuntimeException {
@davidmort wants this as a 404

2019-05-22 09:59 UTC, AdeHarrison commented on src/main/java/uk/gov/ons/census/caseapisvc/service/CaseService.java
> +  private UUID validateAndConvertCaseIdToUUID(String caseId) {
@davidmort wants this as a 404

2019-05-22 10:47 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/caseapisvc/model/entity/Event.java
> +  private EventType eventType;
This is the 'wrong' `EventType` enum, unfortunately - this one is from the DTO package, which we shouldn't use because not all the EventTypes are necessarily going to be sent via message/DTO/API etc. so we should maintain a separate enum of *all* possible DB values (as done in Case Processor).

2019-05-22 10:58 UTC, AdeHarrison commented on src/main/java/uk/gov/ons/census/caseapisvc/model/entity/Event.java
> +  private EventType eventType;
done

2019-05-22 11:38 UTC, NickGrantX approved these changes
LGTM 👍 

Acceptance tests passing.

2019-05-22 13:06 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/caseapisvc/model/entity/Case.java
> +  @Column @Transient private String createdDateTime;
gonna close this PR comment and leave this to be resolved on another ticket

2019-05-22 13:46 UTC, davidmort approved these changes

2019-05-22 13:47 UTC, merged

2019-05-23 08:44 UTC, LukeLoze1 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Update case data model to reflect final rehearsal sample (8)](https://trello.com/c/CzpZXxpZ/741-update-case-data-model-to-reflect-final-rehearsal-sample-8)