Add NonCompliance Model
ONSdigital/census-rm-case-api-2021 pull request #102
Opened 2020-11-16 10:07 UTC by LukeLoze1

# Motivation and Context
For Non Compliance Work

# What has changed

# How to test?
With Case Proc and ATs from ticket

# Links
https://trello.com/c/bEEgKqZY/1404-nc-import-letter-file-1-case-processor-work-8

2020-11-17 15:35 UTC, NickGrantONS requested changes
Breaks the cardinal rule of mixing DTO and entities - the DB needs to change independently of the DTOs, because case data stored in the DB would require patching if there's changes, and equally queues would need draining if DTOs got changed... all of which is horrible if the models are mixed and muddled

2020-11-19 08:03 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/caseapisvc/model/dto/NonComplianceType.java
> +package uk.gov.ons.census.caseapisvc.model.dto;
why does this live in the DTO package and not the entity package?

2020-11-19 08:03 UTC, NickGrantONS requested changes
pls move NCT enum to entity package

2020-11-19 10:04 UTC, LukeLoze1 commented on src/main/java/uk/gov/ons/census/caseapisvc/model/dto/NonComplianceType.java
> +package uk.gov.ons.census.caseapisvc.model.dto;
it was lonely before

2020-11-19 15:46 UTC, NickGrantONS requested changes
Please move enum into entity package

2020-11-20 07:57 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/caseapisvc/model/dto/NonComplianceType.java
> +package uk.gov.ons.census.caseapisvc.model.dto;
please move it into the package with the entity which uses it

2020-11-20 08:46 UTC, LukeLoze1 commented on src/main/java/uk/gov/ons/census/caseapisvc/model/dto/NonComplianceType.java
> +package uk.gov.ons.census.caseapisvc.model.dto;
'git push' found and used.

2020-11-20 10:06 UTC, NickGrantONS approved these changes

2020-11-23 07:29 UTC, NickGrantONS requested changes
You forgot to add `SELECTED_FOR_NON_COMPLIANCE` to the event types, which will cause the Case API to fail when it retrieves an NC case

2020-11-23 15:22 UTC, NickGrantONS approved these changes

2020-11-24 12:02 UTC, hbrace approved these changes

2020-11-24 12:04 UTC, merged