Remove unique number and update test
ONSdigital/census-rm-case-api-2021 pull request #11
Opened 2019-06-27 15:00 UTC by liamtoozer

# Motivation and Context

Unique number is no longer part of the uac-link table so needs to be removed.

# What has changed

* Removed column from uac-qid link table

# How to test?

Run acceptance tests

# Links

https://trello.com/c/cXw970Gx/902-build-uac-not-iac-qid-service-8#

2019-06-27 15:03 UTC, liamtoozer commented
![](https://github.trello.services/images/mini-trello-icon.png) [Build UAC (not IAC!)/QID Service (8)](https://trello.com/c/cXw970Gx/902-build-uac-not-iac-qid-service-8)

2019-07-01 07:24 UTC, AdamHawtin requested changes

2019-07-01 07:24 UTC, AdamHawtin commented on .travis.yml
> +    - model-update
Shouldn't be set to branch build, it'll be building twice for every commit while the PR is open.

2019-07-01 07:24 UTC, AdamHawtin commented on .travis.yml
> +  - if [ "$TRAVIS_BRANCH" == "model-update" ] ; then
Why is this here?

2019-07-01 07:24 UTC, AdamHawtin commented on src/test/resources/docker-compose.yml
> +    image: eu.gcr.io/census-rm-ci/rm/census-rm-case-processor:ade_test
Testing tag committed?

2019-07-01 09:42 UTC, NickGrantX approved these changes
LGTM 👍

2019-07-01 09:45 UTC, AdamHawtin approved these changes

2019-07-01 09:49 UTC, merged