Create uacqid endpoint
ONSdigital/census-rm-case-api-2021 pull request #18
Opened 2019-08-02 12:01 UTC by rjweeks

# Motivation and Context
A new end-point is required that will generate a UAC QID Pair.

# How to test?

# Links
https://trello.com/c/0Jmh2jK2/1003-rmc-134b-synchronous-uac-qid-creation-via-case-api-part-1-5

2019-08-05 13:53 UTC, rjweeks commented
![](https://github.trello.services/images/mini-trello-icon.png) [RMC-134(B) synchronous UAC/QID creation via case api (part 1) (5)](https://trello.com/c/0Jmh2jK2/1003-rmc-134b-synchronous-uac-qid-creation-via-case-api-part-1-5)

2019-08-06 10:32 UTC, AdamHawtin requested changes

2019-08-06 10:32 UTC, AdamHawtin commented on src/main/java/uk/gov/ons/census/caseapisvc/endpoint/UacQidEndpoint.java
> +    int qid = Integer.parseInt(questionnaireType);
I think this should be called `questionnaireType` rather than `qid`, the QID is the full, unique ID whereas this is still just the non-unique type digits.

2019-08-06 10:32 UTC, AdamHawtin commented on src/main/java/uk/gov/ons/census/caseapisvc/model/dto/CaseDetailsDTO.java
> +  @JsonProperty("questionnaire_id")
I think this should be called `questionnaireType` rather than `questionnaire_id`, the QID is the full, unique ID whereas this is still just the non-unique type digits.

2019-08-06 11:36 UTC, rjweeks commented on src/main/java/uk/gov/ons/census/caseapisvc/endpoint/UacQidEndpoint.java
> +    int qid = Integer.parseInt(questionnaireType);
Done

2019-08-06 11:36 UTC, rjweeks commented on src/main/java/uk/gov/ons/census/caseapisvc/model/dto/CaseDetailsDTO.java
> +  @JsonProperty("questionnaire_id")
Done

2019-08-06 11:56 UTC, AdamHawtin approved these changes

2019-08-06 13:09 UTC, davidmort approved these changes

2019-08-06 13:11 UTC, merged