updated readme.md file
ONSdigital/census-rm-case-api-2021 pull request #38
Opened 2019-10-23 12:01 UTC by AdeHarrison

# Motivation and Context
README.md need updating

# What has changed
README updated

# How to test?
no code changes, just read file contents

# Links
[Trello](https://trello.com/c/vag8Mo85/1305-update-readme-for-census-rm-case-api)

# Screenshots (if appropriate):

2019-10-23 12:02 UTC, AdeHarrison commented
![](https://github.trello.services/images/mini-trello-icon.png) [update Readme for census-rm-case-api](https://trello.com/c/vag8Mo85/1305-update-readme-for-census-rm-case-api)

2019-10-23 13:21 UTC, ryangrundy7 approved these changes
LGTM 👍

2019-10-23 13:40 UTC, LukeLoze1 submitted a review, later dismissed

2019-10-23 13:40 UTC, LukeLoze1 commented on README.md
> +* Create and return a new Uac Qid Link
Perhaps worth noting that it also does send on a rabbit msg off when creating a uac.

2019-10-24 07:26 UTC, AdeHarrison commented on README.md
> +* Create and return a new Uac Qid Link
done

2019-10-24 08:04 UTC, NickGrantX requested changes
I know this is onerous, but with API documentation, we've often documented each endpoint with a little more detail (URL, parameters, example JSON). Not sure if this is a job for Swagger or whether you just want to cobble together something from the specs (could always link to the specs I guess).

2019-10-24 12:20 UTC, ryangrundy7 commented on README.md
> +* Create and return a new Uac Qid Link - this resulting
`- this resulting ` not meant to be there?

2019-10-24 13:17 UTC, gavinleeedwards commented
> I know this is onerous, but with API documentation, we've often documented each endpoint with a little more detail (URL, parameters, example JSON). Not sure if this is a job for Swagger or whether you just want to cobble together something from the specs (could always link to the specs I guess).

Agree that as it's an API, it'd be nice to know the endpoints, how they're used, what they return etc.  Similar to what rm business has (https://github.com/ONSdigital/rm-case-service/blob/master/API.md)

2019-10-25 09:33 UTC, AdeHarrison commented on README.md
> +* Create and return a new Uac Qid Link - this resulting
done

2019-10-25 09:37 UTC, NickGrantX approved these changes
Great documentation 👍

2019-10-25 11:08 UTC, merged