Stamp created date
ONSdigital/census-rm-case-api-2021 pull request #5
Opened 2019-05-28 13:07 UTC by AdeHarrison

# Motivation and Context
Populate case created date/time in response

# What has changed

# How to test?
1. using a census-rm-case-api image built from [here](https://github.com/ONSdigital/census-rm-case-processor/pull/17)

2. make test

3. All tests should pass

# Links
[Trello](https://trello.com/c/MysxkDnC/776-defect-case-processor-should-stamp-created-date-or-case-api-should-infer-it-from-events)

# Screenshots (if appropriate):

2019-05-28 13:08 UTC, AdeHarrison commented
![](https://github.trello.services/images/mini-trello-icon.png) [DEFECT: Case processor should stamp created date or Case API should infer it from Events](https://trello.com/c/MysxkDnC/776-defect-case-processor-should-stamp-created-date-or-case-api-should-infer-it-from-events)

2019-05-28 14:04 UTC, NickGrantX requested changes
Unfortunately, the Swagger spec and the convention for returning dates in JSON is to use ISO format and in the Swagger spec it says it should be Zulu time too (i.e. UTC with "Z" on the end). This is a defect, but this PR perpetuates the defect.

2019-05-28 14:11 UTC, NickGrantONS commented on src/test/resources/test_response1_with_events.json
> +  "createdDateTime": "2019-05-28 14:19:00.204",
This should be `2019-05-28T14:19:00.204Z`

2019-05-28 14:11 UTC, NickGrantONS commented on src/test/resources/test_response1_without_events.json
> +  "createdDateTime": "2019-05-28 14:19:00.204",
This should be `2019-05-28T14:19:00.204Z`

2019-05-28 14:12 UTC, NickGrantONS commented on src/test/resources/test_response2_with_events.json
> +  "createdDateTime": "2019-05-28 14:19:00.204",
This should be `2019-05-28T14:19:00.204Z`

2019-05-28 14:12 UTC, NickGrantONS commented on src/test/resources/test_response2_without_events.json
> +  "createdDateTime": "2019-05-28 14:19:00.204",
This should be `2019-05-28T14:19:00.204Z`

2019-05-28 14:13 UTC, NickGrantONS commented on src/test/resources/data-test.sql
> +        'Windleybury', '2019-05-28 14:19:00.204', '123456789012345');
I suggest inserting dates into the DB using ISO format incl. time zone

2019-05-28 14:13 UTC, NickGrantONS commented on src/test/resources/data-test.sql
> +        'Windleybury', '2019-05-28 14:19:00.204', '123456789012345');
I suggest inserting dates into the DB using ISO format incl. time zone

2019-05-29 07:32 UTC, LukeLoze1 requested changes

2019-05-29 07:32 UTC, LukeLoze1 commented on src/main/java/uk/gov/ons/census/caseapisvc/model/entity/Case.java
> +  @Column private Date createdDateTime;
LocalDateTime is usually better than the old Date Type

2019-05-29 12:48 UTC, AdeHarrison commented on src/test/resources/test_response1_with_events.json
> +  "createdDateTime": "2019-05-28 14:19:00.204",
fixed

2019-05-29 12:49 UTC, AdeHarrison commented on src/test/resources/data-test.sql
> +        'Windleybury', '2019-05-28 14:19:00.204', '123456789012345');
fixed

2019-05-29 12:49 UTC, AdeHarrison commented on src/test/resources/data-test.sql
> +        'Windleybury', '2019-05-28 14:19:00.204', '123456789012345');
fixed

2019-05-29 12:49 UTC, AdeHarrison commented on src/main/java/uk/gov/ons/census/caseapisvc/model/entity/Case.java
> +  @Column private Date createdDateTime;
fixed

2019-05-29 12:49 UTC, AdeHarrison commented on src/test/resources/test_response2_without_events.json
> +  "createdDateTime": "2019-05-28 14:19:00.204",
fixed

2019-05-29 12:49 UTC, AdeHarrison commented on src/test/resources/test_response2_with_events.json
> +  "createdDateTime": "2019-05-28 14:19:00.204",
fixed

2019-05-29 12:49 UTC, AdeHarrison commented on src/test/resources/test_response1_without_events.json
> +  "createdDateTime": "2019-05-28 14:19:00.204",
fixed

2019-05-29 12:55 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/caseapisvc/model/entity/Event.java
> +  private Date eventDate;
This type should probably be OffsetDateTime to use the new modern java date types

2019-05-29 12:56 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/caseapisvc/model/dto/CaseContainerDTO.java
> +  private Date createdDateTime;
This type should probably be OffsetDateTime to use the new modern java date types

2019-05-29 12:56 UTC, NickGrantX commented on src/main/java/uk/gov/ons/census/caseapisvc/model/dto/CaseContainerDTO.java
> +  private Date createdDateTime;
This type should probably be OffsetDateTime to use the new modern java date types

2019-05-29 12:56 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/caseapisvc/model/dto/EventDTO.java
> +  private Date eventDate;
This type should probably be OffsetDateTime to use the new modern java date types

2019-05-29 12:57 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/caseapisvc/model/entity/Case.java
> +  private Date createdDateTime;
This type should probably be OffsetDateTime to use the new modern java date types

2019-05-30 08:00 UTC, LukeLoze1 approved these changes

2019-05-30 08:12 UTC, AdeHarrison commented on src/main/java/uk/gov/ons/census/caseapisvc/model/entity/Event.java
> +  private Date eventDate;
changed

2019-05-30 08:12 UTC, AdeHarrison commented on src/main/java/uk/gov/ons/census/caseapisvc/model/dto/CaseContainerDTO.java
> +  private Date createdDateTime;
changed

2019-05-30 08:12 UTC, AdeHarrison commented on src/main/java/uk/gov/ons/census/caseapisvc/model/dto/EventDTO.java
> +  private Date eventDate;
changed

2019-05-30 08:13 UTC, AdeHarrison commented on src/main/java/uk/gov/ons/census/caseapisvc/model/entity/Case.java
> +  private Date createdDateTime;
changed

2019-05-30 10:44 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/caseapisvc/model/entity/Event.java
> +  @Column(columnDefinition = "timestamp with time zone")
don't need this `columnDefinition` anymore I think

2019-05-30 10:45 UTC, NickGrantX requested changes
Just one rogue `columnDefinition` left in

2019-05-30 11:23 UTC, AdeHarrison commented on src/main/java/uk/gov/ons/census/caseapisvc/model/entity/Event.java
> +  @Column(columnDefinition = "timestamp with time zone")
fixed

2019-05-30 12:59 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/caseapisvc/model/entity/Event.java
> +  private OffsetDateTime eventDate;
This needs the `@Column` annotationj

2019-05-30 13:02 UTC, NickGrantX requested changes
Just missing the `@Column` annotation on the `eventDate` member of the `Event` entity

2019-05-30 13:03 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/caseapisvc/model/entity/Event.java
> +  @Column(columnDefinition = "timestamp with time zone")
it does need `@Column` but not the `columnDefinition`

2019-05-30 13:13 UTC, AdeHarrison commented on src/main/java/uk/gov/ons/census/caseapisvc/model/entity/Event.java
> +  private OffsetDateTime eventDate;
done

2019-05-30 13:23 UTC, NickGrantX approved these changes
LGTM 👍

2019-06-03 13:05 UTC, merged