Add find CCS cases by postcode endpoint and tests
ONSdigital/census-rm-case-api-2021 pull request #52
Opened 2020-01-30 13:11 UTC by AdamHawtin

# Motivation and Context
Contact centre needs to be able to search for CCS cases by postcode. 

# What has changed
* Add find CCS cases by postcode endpoint
* Tests for new endpoint

# How to test?
AT's are WIP
Build and run this image with docker dev. Load some CCS cases, you should be able to hit this endpoint with their postcode and get them back.

# Links
https://trello.com/c/RxoE4p0V/522-rmc-221-provide-ccs-case-look-up-by-post-code-8

2020-01-30 13:12 UTC, AdamHawtin commented
![](https://github.trello.services/images/mini-trello-icon.png) [RMC-221 Provide CCS case look up by post code (8)](https://trello.com/c/RxoE4p0V/522-rmc-221-provide-ccs-case-look-up-by-post-code-8)

2020-01-31 11:05 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/caseapisvc/model/repository/CaseRepository.java
> +      "SELECT c FROM Case c WHERE survey='CCS' AND UPPER(REPLACE(postcode, ' ', '')) LIKE UPPER(REPLACE(:postcode, ' ', ''))")
why does it need to be a `LIKE` if you're not using the `%` wildcard? You could just use a regular `=`

2020-01-31 11:07 UTC, NickGrantX requested changes
At the moment we're allowing partial postcode searches because you've used `LIKE`. This might be by design, but in theory, somebody could retrieve 400,000 results just by searching for `%`

2020-01-31 11:27 UTC, LukeLoze1 approved these changes

2020-01-31 11:29 UTC, AdamHawtin commented
@NickGrantONS Yes, it doesn't not need to be a `LIKE`, I've changed it to an equals comparison.

2020-02-03 11:34 UTC, NickGrantX approved these changes
Looks good. Performance testing probably not important because this'll be called relatively infrequently.

2020-02-03 11:35 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/caseapisvc/model/repository/CaseRepository.java
> +      "SELECT c FROM Case c WHERE survey='CCS' AND UPPER(REPLACE(postcode, ' ', '')) LIKE UPPER(REPLACE(:postcode, ' ', ''))")
Actually you still need to address this review comment

2020-02-03 11:35 UTC, NickGrantX requested changes
Still need to replace that `LIKE` with an `=`

2020-02-03 11:40 UTC, NickGrantX approved these changes
Looks good 👍

2020-02-03 13:13 UTC, merged