handle Individual Telephone requests for SPG Unit cases
ONSdigital/census-rm-case-api-2021 pull request #54
Opened 2020-01-31 13:37 UTC by LukeLoze1

# Motivation and Context
Correctly handle individual telephone requests for SPG Unit cases

# What has changed
Checks if case is type SPG/U if so handles slightly differently 

# How to test?
With other apps from ticket

# Links
https://trello.com/c/G23nV6a7/506-spg-individual-tel-capture-for-unit-case-5

2020-02-03 09:25 UTC, AdamHawtin requested changes
Builds/passes AT's, just a comment about what level we put logic at.

2020-02-03 09:25 UTC, AdamHawtin commented on src/main/java/uk/gov/ons/census/caseapisvc/endpoint/CaseEndpoint.java
> +    }
Could the checking of case type/address type be left to the `...handleRequest` functions? Up till now this endpoint function has only explicitly inspected/conditioned on the request parameters and handed off inspecting the case to the functions it calls, it would be nice to keep this pattern if possible. Won't block on this if the logic makes this too awkward though.

2020-02-03 10:33 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/caseapisvc/endpoint/CaseEndpoint.java
> +    }
yeah, I agree with Adam. The code in the endpoint class should concern itself with "is this a valid request?" and return a 400 BAD REQUEST if it's not. The business logic should live in the service class, if we're going to break things up logically.

2020-02-03 10:35 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/caseapisvc/endpoint/CaseEndpoint.java
> +    }
I'd also much prefer to have optional arguments wrapped in an `Optional<?>` class, so we can test if a parameter is present or not... although it's kinda out of scope refactoring

2020-02-04 12:19 UTC, NickGrantX approved these changes
Would have been nice to see some of the suggested refactoring, but I guess the code is syntactically correct and it compiles. Good job.

2020-02-04 14:05 UTC, AdamHawtin approved these changes

2020-02-04 14:06 UTC, merged