Added hand delivery flag to dto and model
ONSdigital/census-rm-case-api-2021 pull request #62
Opened 2020-02-14 15:27 UTC by ryangrundy7

# Motivation and Context

- Added hand delivery to case container dto.

# How to test?

 
- Run with other branches and test with acceptance tests.

# Links

https://trello.com/c/774V6fGU/580-add-handdelivery-flag-to-casecreated-and-caseupdated-events-and-case-api-8
# Screenshots (if appropriate):

2020-02-14 15:37 UTC, ryangrundy7 commented
![](https://github.trello.services/images/mini-trello-icon.png) [add handDelivery flag to caseCreated and caseUpdated events and case API (8)](https://trello.com/c/774V6fGU/580-add-handdelivery-flag-to-casecreated-and-caseupdated-events-and-case-api-8)

2020-02-17 10:37 UTC, AdamHawtin commented on src/main/java/uk/gov/ons/census/caseapisvc/model/dto/CaseContainerDTO.java
> +  private Boolean handDelivery;
If we're never sending `null` or missing this value off we can make this a `boolean` instead.

2020-02-17 10:37 UTC, AdamHawtin commented on src/main/java/uk/gov/ons/census/caseapisvc/model/entity/Case.java
> +  @Column(columnDefinition = "BOOLEAN")
Column definition shouldn't be necessary, same as case service

2020-02-17 10:59 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/caseapisvc/model/dto/CaseContainerDTO.java
> +  private Boolean handDelivery;
we'd have to change the underlying DB type too, or make it non-nullable

2020-02-17 11:04 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/caseapisvc/model/dto/CaseContainerDTO.java
> +  private Boolean handDelivery;
make this `boolean` not `Boolean` to match the underlying entity

2020-02-17 11:05 UTC, NickGrantX requested changes
What Adam said

2020-02-17 14:22 UTC, AdamHawtin requested changes

2020-02-17 14:22 UTC, AdamHawtin commented on src/main/java/uk/gov/ons/census/caseapisvc/model/entity/Case.java
> +  private boolean handDelivery;
Needs `@Column(nullable = false, columnDefinition = "BOOLEAN DEFAULT false")` to match the DDL

2020-02-18 12:15 UTC, AdamHawtin approved these changes

2020-02-18 12:19 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/caseapisvc/model/entity/Case.java
> +  @Column(nullable = false, columnDefinition = "BOOLEAN DEFAULT false")
`nullable = false` is implied, but not going to block it on such a minor point

2020-02-18 12:19 UTC, NickGrantX approved these changes
`nullable = false` is implied on any `boolean` value, but I'm not going to block it on such a minor point. Looks good 👍

2020-02-18 14:34 UTC, merged