addressType and caseType confusion
ONSdigital/census-rm-case-api-2021 pull request #64
Opened 2020-03-03 14:30 UTC by LeoKHoward

# Motivation and Context
Case in case-api now has both caseType and addressType but we call the addressType "caseType" in the JSON messages we return so it can be confusing

# What has changed
Now when JSON is returned, caseType is called addressType

# How to test?
Clone, build and run IT and unit tests
Get case ref from DB and check that the JSON from likes of Case Ref (http://localhost:8161/cases/ref/{reference) returns addressType instead of caseType

# Links
https://trello.com/c/FlnWxlG2
https://collaborate2.ons.gov.uk/confluence/display/CATD/Case+API

2020-03-03 14:32 UTC, LeoKHoward commented
![](https://github.trello.services/images/mini-trello-icon.png) [Sort out addressType/caseType confusion in Case API (3)](https://trello.com/c/FlnWxlG2/566-sort-out-addresstype-casetype-confusion-in-case-api-3)

2020-03-03 15:38 UTC, AdamHawtin requested changes

2020-03-03 15:38 UTC, AdamHawtin commented on src/main/java/uk/gov/ons/census/caseapisvc/model/dto/CaseContainerDTO.java
> +  @JsonProperty("addressType")
We don't need the `@JsonProperty` when the name is the same as the variable name

2020-03-04 08:54 UTC, hbrace approved these changes

2020-03-04 09:06 UTC, AdamHawtin approved these changes

2020-03-04 09:41 UTC, merged