Add CE Secure Marker
ONSdigital/census-rm-case-api-2021 pull request #67
Opened 2020-03-10 15:12 UTC by LeoKHoward

# Motivation and Context
New column for identifying if CE case is a Secure Establishment

# What has changed
New ceSecure/secureEstablishment column 
Tests

# How to test?
Clone the branch and run ```maven clean install``` which will build the image

# Links
https://collaborate2.ons.gov.uk/confluence/display/CRM/Address+Frame+specification+2021?focusedCommentId=36183836#comment-36183836
https://trello.com/c/BAI9qOOC/619-rmc-341-add-secure-marker-case-api-and-field-8

2020-03-10 16:03 UTC, LeoKHoward commented
![](https://github.trello.services/images/mini-trello-icon.png) [RMC-341 Add secure marker - case api and field (8)](https://trello.com/c/BAI9qOOC/619-rmc-341-add-secure-marker-case-api-and-field-8)

2020-03-12 13:17 UTC, AdamHawtin requested changes

2020-03-12 13:17 UTC, AdamHawtin commented on src/main/java/uk/gov/ons/census/caseapisvc/endpoint/CaseEndpoint.java
> +    //    }
Commented out null check should either be deleted or reinstated

2020-03-12 14:06 UTC, LukeLoze1 commented on src/main/java/uk/gov/ons/census/caseapisvc/endpoint/CaseEndpoint.java
> +    //    }
I'm presuming if this passes the ATs with it commented out then it's 'probably' not needed

2020-03-12 14:56 UTC, LukeLoze1 commented on src/test/java/uk/gov/ons/census/caseapisvc/endpoint/CaseEndpointIT.java
> +  @Test
Not super keen on having 2 new Integration Tests just to check a field is being set correctly. Won't block the ticket on it.  I'd like to see that Endpoint and it's tests refactored, there's 1083 lines in the CaseEndpointITs, this seems mad, mad I tell you.

2020-03-12 14:57 UTC, LukeLoze1 reviewed
Remove commented out code

2020-03-13 12:28 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/caseapisvc/endpoint/CaseEndpoint.java
> +    //    }
yes the code that's commented out needs to be deleted

2020-03-13 12:30 UTC, NickGrantONS commented on src/test/java/uk/gov/ons/census/caseapisvc/endpoint/CaseEndpointIT.java
> +  @Test
at least they run quite quickly. Each test is also quite short. It's only test code and it has good coverage, and it's easy to edit if a test fails.

2020-03-13 12:32 UTC, NickGrantONS commented on src/test/java/uk/gov/ons/census/caseapisvc/endpoint/CaseEndpointIT.java
> +  @Test
The problem is that we're starting to get "God Classes" that do everything including the kitchen sink. Combining telephone capture, fulfilments, plus general CRUD crap all into one place is the real problem here.

2020-03-13 12:33 UTC, NickGrantX approved these changes
LGTM. Ignore the haters.

Haters gonna hate.

2020-03-13 12:33 UTC, AdamHawtin submitted a review, later dismissed

2020-03-13 12:33 UTC, AdamHawtin commented on src/main/java/uk/gov/ons/census/caseapisvc/endpoint/CaseEndpoint.java
> +    //    }
The lack of null check here seems to be causing the AT failures, for CCS cases it's throwing NPE's

2020-03-13 12:54 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/caseapisvc/endpoint/CaseEndpoint.java
> +    //    }
hmmm good point. The null check isn't going to hurt

2020-03-13 16:25 UTC, LeoKHoward commented on src/main/java/uk/gov/ons/census/caseapisvc/endpoint/CaseEndpoint.java
> +    //    }
Have put it back in and the CCS tests now pass so will be keeping it

2020-03-17 09:23 UTC, LukeLoze1 commented on src/test/java/uk/gov/ons/census/caseapisvc/endpoint/CaseEndpointIT.java
> +  @Test
I like the term 'God Classes'

2020-03-17 09:23 UTC, LukeLoze1 approved these changes

2020-03-17 12:01 UTC, merged