alter invalidAddressQueue to addressQueue
ONSdigital/census-rm-case-api-2021 pull request #69
Opened 2020-03-20 09:00 UTC by LukeLoze1

# Motivation and Context
NewAddressReported handling

# What has changed
new field for SkellingtonCasee

# How to test?
with other branchs on this ticket

# Links
https://trello.com/c/qixf5J2X/594-am1-part-1-new-address-reported-event-13

2020-03-25 13:39 UTC, hbrace approved these changes

2020-03-27 09:35 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/caseapisvc/model/entity/Case.java
> +  private boolean skellington;
It's spelled _skeleton_

2020-03-27 09:36 UTC, NickGrantX requested changes
It's vital that we name things which people are searching the codebase for without typos

2020-03-30 08:07 UTC, NickGrantX approved these changes
LGTM 👍

2020-03-30 11:35 UTC, merged