Push metrics into Stackdriver
ONSdigital/census-rm-case-api-2021 pull request #79
Opened 2020-05-19 09:00 UTC by NickGrantONS

# Motivation and Context
We want to push metrics into Stackdriver instead of scraping the metrics out using Prometheus.

# What has changed
Added Micrometer Stackdriver registry and config to push metrics into Stackdriver.

# How to test?
Use k8s deployment to test in GCP environment.

# Links
Trello: https://trello.com/c/98bq2JmZ

2020-05-19 09:04 UTC, NickGrantONS commented
![](https://github.trello.services/images/mini-trello-icon.png) [case-api & uac qid service response time monitoring](https://trello.com/c/98bq2JmZ/814-case-api-uac-qid-service-response-time-monitoring)

2020-05-21 08:13 UTC, davidmort requested changes

2020-05-21 08:13 UTC, davidmort commented on src/main/java/uk/gov/ons/census/caseapisvc/config/AppConfig.java
> +        return "Case API";
this should be the current projectId, can use management.metrics.export.stackdriver.project-id config item for this

2020-05-22 10:10 UTC, AdamHawtin approved these changes

2020-05-22 10:10 UTC, AdamHawtin approved these changes

2020-05-22 11:28 UTC, davidmort approved these changes

2020-05-22 11:35 UTC, merged