Update Refusal Logic
ONSdigital/census-rm-case-api-2021 pull request #81
Opened 2020-06-01 09:23 UTC by LeoKHoward

# Motivation and Context
New changes to refusal types. Need to be able to change refusal types and stop reminders/visits where necessary 

# What has changed
Column type changed from boolean to string

# How to test?
Build image with rest of repos on card and run ATs

# Links
https://trello.com/c/tnVfjzpv/710-update-refusal-logic-8

2020-06-01 09:42 UTC, LeoKHoward commented
![](https://github.trello.services/images/mini-trello-icon.png) [Update Refusal logic (8)](https://trello.com/c/tnVfjzpv/710-update-refusal-logic-8)

2020-06-01 13:25 UTC, LukeLoze1 approved these changes

2020-06-02 08:19 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/caseapisvc/model/entity/Case.java
> +  @Column private String refusalReceived;
Should use enum

2020-06-02 08:19 UTC, NickGrantX requested changes
Needs to use enum to meet coding standards

2020-06-03 07:33 UTC, NickGrantX approved these changes
LGTM 👍

2020-06-03 07:44 UTC, AdamHawtin approved these changes

2020-06-03 12:27 UTC, merged