Add new param to uprn endpoint
ONSdigital/census-rm-case-api-2021 pull request #83
Opened 2020-06-09 08:59 UTC by gavinleeedwards

# Motivation and Context
Add optional validAddressOnly parameter to 'search by UPRN' endpoint.

# What has changed
- When searching for cases by UPRN, if `validAddressOnly=true` then only cases where `addressInvalid=false` will be returned.
- If `validAddressOnly=false` or the parameter is omitted then all matching cases will be returned (as per current functionality) 

# How to test?
- Call the `/cases/uprn/<uprn>` endpoint with:
  - `?validAddressOnly=true`  - Only cases that match the UPRN and have addressInvalid=false will be returned
  - `?validAddressOnly=false`  - All cases that match the UPRN will be returned
  - No param - All cases that match the UPRN will be returned

# Links
- https://trello.com/c/7JkD3btb

2020-06-09 09:00 UTC, gavinleeedwards commented
![](https://github.trello.services/images/mini-trello-icon.png) [Case API update - invalidAddress flag (5)](https://trello.com/c/7JkD3btb/991-case-api-update-invalidaddress-flag-5)

2020-06-10 10:42 UTC, ryangrundy7 commented on src/main/java/uk/gov/ons/census/caseapisvc/service/CaseService.java
> +          .orElseThrow(() -> new UPRNNotFoundException(uprn));
You can simplify this bit by removing the `== true` and just having `if (validAddressOnly)`. Instead of `findByUprnAndAddressInvalidNot ` you can just say addressInvalidIsFalse so you don't need to pass in the true

2020-06-11 06:56 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/caseapisvc/model/dto/CaseContainerDTO.java
> +  private Boolean addressInvalid;
I would make this `boolean` instead of `Boolean` so that it matches the `Case` entity

2020-06-11 06:58 UTC, NickGrantX requested changes
One minor comments

2020-06-11 07:55 UTC, ryangrundy7 approved these changes
LGTM 👍

2020-06-12 09:05 UTC, NickGrantX approved these changes
LGTM 👍

2020-06-12 10:41 UTC, merged