Update entities
ONSdigital/census-rm-case-api-2021 pull request #9
Opened 2019-06-12 08:21 UTC by AdeHarrison

# Motivation and Context

# What has changed

# How to test?

# Links

# Screenshots (if appropriate):

2019-06-12 09:42 UTC, AdeHarrison commented
![](https://github.trello.services/images/mini-trello-icon.png) [RMC-152(A) Receipting should update case and UAC active flag (8)](https://trello.com/c/GdA7flOq/788-rmc-152a-receipting-should-update-case-and-uac-active-flag-8)

2019-06-17 14:05 UTC, NickGrantX requested changes
`Case.receiptReceived` and `UacQidLink.active` have not been replicated - the entity models are drifting apart.

Perhaps it's time to consider that it was a mistake to have `census-rm-case-api` in a different project from `census-rm-case-processor` and go for the monorepo (with two Maven submodules) as was suggested, because there's a constant risk that the JPA entities will drift out of sync with each other, as this PR has shown.

2019-06-25 11:03 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/caseapisvc/model/entity/Case.java
> +      cascade = {CascadeType.ALL})
I can understand that this cascade makes it easier to use the `.deleteAll()` convenience method on the repo, but I worry about having the entity classes differ from the ones in `census-rm-case-processor` given that we're sharing the underlying schema. This cascade is only here for testing purposes - is there another way to clear out the test data or do we not have the repos so we can clear out each table individually in the correct sequence?

2019-06-25 11:05 UTC, NickGrantX requested changes
Still needs work - looks like the entity POJOs are getting more and more different from the ones in Case Processor, which is going to make keeping them in sync a pain

2019-06-25 11:55 UTC, NickGrantX approved these changes

2019-06-25 11:56 UTC, NickGrantONS commented
We should put the `cascade` settings into the entities in Case Processor so that they match 1:1

2019-06-25 12:00 UTC, rjweeks approved these changes

2019-06-25 12:49 UTC, merged