View All Case Details
ONSdigital/census-rm-case-api-2021 pull request #94
Opened 2020-08-27 13:27 UTC by LeoKHoward

# Motivation and Context
Offers user ability to view all case and event details of selected case

# What has changed
New case endpoint api
New Case Details DTO
Excludes data for RM_UAC_CREATED event
Tests

# How to test?
Build image and run on ops-ui branch. Select a case and check you can see the details

# Links
https://trello.com/c/ZxxGq4aT/1222-r-ops-ui-view-all-case-details-13
https://rops-prototypes.netlify.app/prototypes/rops-management/version-2/1-acacia-avenue/index.html

2020-08-27 13:29 UTC, LeoKHoward commented
![](https://github.trello.services/images/mini-trello-icon.png) [R Ops UI - View all case details (13)](https://trello.com/c/ZxxGq4aT/1222-r-ops-ui-view-all-case-details-13)

2020-08-27 14:19 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/caseapisvc/endpoint/CaseEndpoint.java
> +          continue;
it's fewer lines of code if you did:
```
if (!event.getEventType().equals(EventType.RM_UAC_CREATED)) {
  caseEvents.add(mapperFacade.map(event, CaseDetailsEventDTO.class));
}
```

2020-08-27 14:21 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/caseapisvc/endpoint/CaseEndpoint.java
> +        caseEvents.add(mapperFacade.map(event, CaseDetailsEventDTO.class));
This also needs to filter out `RM_UAC_CREATED` events

2020-08-27 14:22 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/caseapisvc/model/dto/CaseDetailsDTO.java
> +  @JsonProperty("id")
The repurposing of this class makes me nervous

2020-08-27 14:24 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/caseapisvc/model/dto/CaseDetailsDTO.java
> +  @JsonProperty("id")
okay I checked and this was dead code (grrr) so it's cool that you re-used it

2020-08-27 14:24 UTC, NickGrantONS requested changes
Very minor comments

2020-08-27 14:27 UTC, ryangrundy7 commented on src/main/java/uk/gov/ons/census/caseapisvc/model/dto/CaseDetailsDTO.java
> +  @JsonProperty("id")
Don't think that DTO was ever used for anything before so maybe okay to add to it

2020-08-28 06:23 UTC, AdamHawtin commented on src/main/java/uk/gov/ons/census/caseapisvc/endpoint/CaseEndpoint.java
> +  @GetMapping(value = "/case_details/{case_id}")
Normal convention in URL's is dashes rather than underscores  
```suggestion
  @GetMapping(value = "/case-details/{case_id}")
```

2020-09-01 13:26 UTC, AdamHawtin commented on src/main/java/uk/gov/ons/census/caseapisvc/endpoint/CaseEndpoint.java
> +        if (!event.getEventType().equals(EventType.RM_UAC_CREATED)) {
Perhaps a comment on why we're redacting these specific events?

2020-09-01 13:45 UTC, AdamHawtin commented on src/main/java/uk/gov/ons/census/caseapisvc/endpoint/CaseEndpoint.java
> +  @GetMapping(value = "/case-details/{case_id}")
The other endpoints all use `caseId` instead of `case_id`

2020-09-01 13:46 UTC, AdamHawtin approved these changes
Would be nice to use the same `caseId` parameter but consistency is for porridge 🥣 
👍

2020-09-02 06:30 UTC, NickGrantONS approved these changes

2020-09-02 07:54 UTC, merged