Add get and link QID endpoints
ONSdigital/census-rm-case-api-2021 pull request #97
Opened 2020-09-04 11:42 UTC by AdamHawtin

# Motivation and Context

# What has changed

# How to test?

# Links

# Screenshots (if appropriate):

2020-09-16 08:49 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/caseapisvc/model/dto/QidLink.java
> +public class QidLink {
Needs to include the desired transaction ID, which will also be audit logged by the ROps UI

2020-09-16 08:50 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/caseapisvc/service/UacQidService.java
> +    EventDTO eventDTO = new EventDTO();
I'm tempted to say that the channel should be "ROPS_UI" to differentiate this event from stuff that's been done by the contact centre

2020-09-16 08:50 UTC, NickGrantONS requested changes
See comments

2020-09-16 08:56 UTC, NickGrantONS commented on src/test/java/uk/gov/ons/census/caseapisvc/endpoint/CaseEndpointIT.java
> +    // TODO This test can fail intermittently, needs improving
I can pair up with you, implementing the `QueueSpy` pattern in the CaseApi integration tests, which I think will massively improve things

2020-09-16 12:28 UTC, ryangrundy7 commented on src/main/java/uk/gov/ons/census/caseapisvc/model/dto/QidLink.java
> +public class QidLink {
Added transaction id 👍

2020-09-16 12:29 UTC, ryangrundy7 commented on src/main/java/uk/gov/ons/census/caseapisvc/service/UacQidService.java
> +    EventDTO eventDTO = new EventDTO();
Passed in ROPS_UI as channel

2020-09-18 14:05 UTC, NickGrantONS approved these changes

2020-09-23 07:55 UTC, NickGrantONS requested changes
ITs broken.

Need to add `case.rm.unInvalidateAddress` queue to rabbit config

2020-09-23 07:58 UTC, NickGrantONS approved these changes
False alarm! All good

2020-09-23 08:48 UTC, liamtoozer approved these changes

2020-09-23 08:58 UTC, merged