1271 ccs telephone capture
ONSdigital/census-rm-case-api-2021 pull request #99
Opened 2020-09-14 11:38 UTC by LukeLoze1

# Motivation and Context
CCS telephone capture

# What has changed
Handle CCS

# How to test?
mvn clean install and run ATs

# Links
https://trello.com/c/0T2BpkTE/1271-ccs-telephone-capture-5

2020-09-17 07:47 UTC, ryangrundy7 commented on src/test/java/uk/gov/ons/census/caseapisvc/service/UacQidServiceTest.java
> +        UacQidService.calculateQuestionnaireType("HH", "E1000", "CENSUS", ADDRESS_LEVEL_UNIT);
This test is making `CENSUS` the address_level field

2020-09-17 08:57 UTC, ryangrundy7 approved these changes
LGTM 👍

2020-09-17 12:22 UTC, LeoKHoward approved these changes
Works for me

2020-09-23 07:38 UTC, NickGrantONS requested changes
won't build for me

2020-09-24 11:44 UTC, NickGrantONS approved these changes
Builds for me now 👍

2020-09-24 13:00 UTC, merged